### ISSUE TITLE
New Feature: Cloud Layers

### ISSUE THREAD

**Issue by amantvfx** [True-VFX/TrueSKY#15]
Add a layering system for Clouds, allowing users to combine different types of clouds.

### To-Do

- [ ] **UI Changes**  
  - **Option 1:** Keep the existing UI and add a button to add extra layers. After pressing the button, a UIList is shown. This keeps the UI simple since many users will use only one layer.  
  - **Option 2:** Start with a UIList by default, allowing layers to be added using a '+' button. This would work like True-Terrain Layers. Preset options will appear in a popup (similar to TT).

- [ ] **Basic Layer Functions**  
  - Add  
  - Remove  
  - Move up/down  
  - Duplicate  

- [ ] **Layer-Specific Settings**  
  - Height for each layer  
  - Gap between layers  

- [ ] **Node Group Adjustments**  
  Make any required changes to the node groups to improve how layers interact.

**Comment by zachEastin** [comment]
closing due to duplicate/new Issue #4
